name: Generate web page

on:
  push:
    branches: '*'
    paths:
      - 'lib/*'
      - 'index.tt'
      - 'makecal'
      - 'cpanfile'
  schedule:
    - cron: '22 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: perldocker/perl-tester:5.36

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install libraries
      run: |
          apt-get update -y
          apt-get install -y cpanminus

    - name: Install modules
      run: |
          cpanm --installdeps --notest .

    - name: Create pages
      run: |
        mkdir -p docs
        perl makecal > towerbridge.log 2>&1

    - name: Commit new page
      if: github.repository == 'davorg/towerbridge'
      run: |
        git config --global --add safe.directory /__w/towerbridge/towerbridge
        GIT_STATUS=$(git status --porcelain)
        echo $GIT_STATUS
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add docs/
        if [ "$GIT_STATUS" != "" ]; then git commit -m "Automated Web page generation"; fi
        if [ "$GIT_STATUS" != "" ]; then git push; fi

    - name: Update pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/

    - name: Archive build logs
      uses: actions/upload-artifact@v3
      with:
        name: towerbridge.log
        path: ./towerbridge.log
        retention-days: 3

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
